name: deploy

on:
    push:
        branches: ['main', 'dev']
    pull_request:
        branches: ['main', 'dev']

env:
    APP_SECRET: ${{ secrets.APP_SECRET }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    NAME_APP: "MyDocs"
    MAIL_FROM_EMAIL=${{ secrets.MAIL_FROM_EMAIL }}
    MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}

jobs:
    avoid_redundancy:
        runs-on: ubuntu-22.04
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                  access_token: ${{ github.token }}
    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci --no-fund --no-audit --no-warnings

            - name: Run linter
              run: npm run lint

    test:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x
                  cache: 'npm'
            - name: Install dependencies
              run: npm ci --no-fund --no-audit --no-progress --no-warnings
            - name: Run tests
              run: npm run test

    build:
        runs-on: ubuntu-22.04
        needs: [lint, test]
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Use Node.js 22.x
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci --no-fund --no-audit --no-progress --no-warnings
            - name: Run build
              run: npm run build

    deploy:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        needs: build
        runs-on: ubuntu-22.04
        container: ghcr.io/railwayapp/cli:latest
        env:
            SVC_ID: my-service-id
            RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Deploy to Hosting
              run: railway up --service=${{ secrets.SVC_ID }}
