name: Node.js CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main', 'dev']
jobs:
    build:
        runs-on: ubuntu-24.04
        env:
            DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }} # Agrega esta línea
            JWT_SECRET: ${{ secrets.JWT_SECRET }} # Agrega esta línea
        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Create .env file
              run: |
                  echo "DATABASE_URL_TEST=${{ secrets.DATABASE_URL_TEST }}" >> .env
                  echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
                  # Agrega otras variables de entorno necesarias aquí
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install dependencies
              run: npm install
            - name: Run linter
              run: npm run lint
            - name: Generate Prisma Client (test)
              run: npx prisma generate --schema=prisma/schema.test.prisma
            - name: Generate Prisma Client (production)
              run: npx prisma generate --schema=prisma/schema.production.prisma
            - name: Run tests
              run: npm run test
            - name: Run build
              run: npm run build
